import * as opcodes from './OperationCodes'
import {reg8, flags} from './Memory'

export default OperationCodesMapping = [
  //0X00
  opcodes.NOP,
  opcodes.LD_XY_d16.bind(undefined, reg8.B, reg8.C),
  opcodes.LD_mXY_Z.bind(undefined, reg8.B, reg8.C, reg8.A),
  opcodes.INC_XY.bind(undefined, reg8.B, reg8.C),
  opcodes.INC_X.bind(undefined, reg8.B),
  opcodes.DEC_X.bind(undefined, reg8.B),
  opcodes.LD_X_d8.bind(undefined, reg8.B),
  opcodes.RLC_X.bind(undefined, reg8.A),
  opcodes.LD_a16_SP,
  opcodes.ADD_XY_ZQ.bind(undefined, reg8.H, reg8.L, reg8.B, reg8.C),
  opcodes.LD_X_mYZ.bind(undefined, reg8.A, reg8.B, reg8.C),
  opcodes.DEC_XY.bind(undefined, reg8.B, reg8.C),
  opcodes.INC_X.bind(undefined, reg8.C),
  opcodes.DEC_X.bind(undefined, reg8.C),
  opcodes.LD_X_d8.bind(undefined, reg8.C),
  opcodes.RRC_X.bind(undefined, reg8.A),
  //0x10
  opcodes.STOP,
  opcodes.LD_XY_d16.bind(undefined, reg8.D, reg8.E),
  opcodes.LD_mXY_Z.bind(undefined, reg8.D, reg8.E, reg8.A),
  opcodes.INC_XY.bind(undefined, reg8.D, reg8.E),
  opcodes.INC_X.bind(undefined, reg8.D),
  opcodes.DEC_X.bind(undefined, reg8.D),
  opcodes.LD_X_d8.bind(undefined, reg8.D),
  opcodes.RL_X.bind(undefined, reg8.A),
  opcodes.JR_r8,
  opcodes.ADD_XY_ZQ.bind(undefined, reg8.H, reg8.L, reg8.D, reg8.E),
  opcodes.LD_X_mYZ.bind(undefined, reg8.A, reg8.D, reg8.E),
  opcodes.DEC_XY.bind(undefined, reg8.D, reg8.E),
  opcodes.INC_X.bind(undefined, reg8.E),
  opcodes.DEC_X.bind(undefined, reg8.E),
  opcodes.LD_X_d8.bind(undefined, reg8.E),
  opcodes.RR_X,
  //0x20
  opcodes.JR_SF_r8.bind(undefined, false, flags.zero),
  opcodes.LD_XY_d16.bind(undefined, reg8.H, reg8.L),
  opcodes.LD_N_mXY_Z.bind(undefined,1, reg8.H, reg8.L, reg8.A),
  opcodes.INC_XY.bind(undefined, reg8.H, reg8.L),
  opcodes.INC_X.bind(undefined, reg8.H),
  opcodes.DEC_X.bind(undefined, reg8.H),
  opcodes.LD_X_d8.bind(undefined, reg8.H),
  opcodes.DAX.bind(undefined, reg8.A),
  opcodes.JR_SF_r8.bind(undefined, true, flags.zero),
  opcodes.ADD_XY_ZQ.bind(undefined, reg8.H, reg8.L, reg8.H, reg8.L),
  opcodes.LD_N_X_mYZ.bind(undefined,1, reg8.A, reg8.H, reg8.L),
  opcodes.DEC_XY.bind(undefined, reg8.H, reg8.L),
  opcodes.INC_X.bind(undefined, reg8.L),
  opcodes.DEC_X.bind(undefined, reg8.L),
  opcodes.LD_X_d8.bind(undefined, reg8.L),
  opcodes.CPL_X.bind(undefined, reg8.A),
  //0x30
  opcodes.JR_SF_r8.bind(undefined, false, flags.carry),
  opcodes.LD_XY_d16.bind(undefined, reg8.S, reg8.P),
  opcodes.LD_N_mXY_Z.bind(undefined, -1, reg8.H, reg8.L),
  opcodes.INC_XY.bind(undefined, reg8.S, reg8.P),
  opcodes.INC_mXY.bind(undefined, reg8.H, reg8.L),
  opcodes.DEC_mXY.bind(undefined, reg8.H, reg8.L),
  opcodes.LD_mXY_d8.bind(undefined, reg8.H, reg8.L),
  opcodes.SCF,
  opcodes.JR_SF_r8.bind(undefined, true, flags.carry),
  opcodes.ADD_XY_ZQ.bind(undefined, reg8.H, reg8.L, reg8.S, reg8.P),
  opcodes.LD_N_X_mYZ.bind(undefined,-1,reg8.A,reg8.H, reg8.L),
  opcodes.DEC_XY.bind(undefined, reg8.S, reg8.P),
  opcodes.INC_X.bind(undefined, reg8.A),
  opcodes.DEC_X.bind(undefined, reg8.A),
  opcodes.LD_X_d8.bind(undefined, reg8.A),
  opcodes.CCF,
  //0x40
  opcodes.LD_X_Y.bind(undefined, reg8.B, reg8.B),
  opcodes.LD_X_Y.bind(undefined, reg8.B, reg8.C),
  opcodes.LD_X_Y.bind(undefined, reg8.B, reg8.E),
  opcodes.LD_X_Y.bind(undefined, reg8.B, reg8.D),
  opcodes.LD_X_Y.bind(undefined, reg8.B, reg8.H),
  opcodes.LD_X_Y.bind(undefined, reg8.B, reg8.L),
  opcodes.LD_X_mYZ.bind(undefined, reg8.B, reg8.H, reg8.L),
  opcodes.LD_X_Y.bind(undefined, reg8.B, reg8.A),
  opcodes.LD_X_Y.bind(undefined, reg8.C, reg8.B),
  opcodes.LD_X_Y.bind(undefined, reg8.C, reg8.C),
  opcodes.LD_X_Y.bind(undefined, reg8.C, reg8.D),
  opcodes.LD_X_Y.bind(undefined, reg8.C, reg8.E),
  opcodes.LD_X_Y.bind(undefined, reg8.C, reg8.H),
  opcodes.LD_X_Y.bind(undefined, reg8.C, reg8.L),
  opcodes.LD_X_mYZ.bind(undefined, reg8.C, reg8.H, reg8.L),
  opcodes.LD_X_Y.bind(undefined, reg8.C, reg8.A),
  //0x50
  opcodes.LD_X_Y.bind(undefined, reg8.D, reg8.B),
  opcodes.LD_X_Y.bind(undefined, reg8.D, reg8.C),
  opcodes.LD_X_Y.bind(undefined, reg8.D, reg8.E),
  opcodes.LD_X_Y.bind(undefined, reg8.D, reg8.D),
  opcodes.LD_X_Y.bind(undefined, reg8.D, reg8.H),
  opcodes.LD_X_Y.bind(undefined, reg8.D, reg8.L),
  opcodes.LD_X_mYZ.bind(undefined, reg8.D, reg8.H, reg8.L),
  opcodes.LD_X_Y.bind(undefined, reg8.D, reg8.A),
  opcodes.LD_X_Y.bind(undefined, reg8.E, reg8.B),
  opcodes.LD_X_Y.bind(undefined, reg8.E, reg8.C),
  opcodes.LD_X_Y.bind(undefined, reg8.E, reg8.D),
  opcodes.LD_X_Y.bind(undefined, reg8.E, reg8.E),
  opcodes.LD_X_Y.bind(undefined, reg8.E, reg8.H),
  opcodes.LD_X_Y.bind(undefined, reg8.E, reg8.L),
  opcodes.LD_X_mYZ.bind(undefined, reg8.E, reg8.H, reg8.L),
  opcodes.LD_X_Y.bind(undefined, reg8.E, reg8.A),
  //0x60
  opcodes.LD_X_Y.bind(undefined, reg8.H, reg8.B),
  opcodes.LD_X_Y.bind(undefined, reg8.H, reg8.C),
  opcodes.LD_X_Y.bind(undefined, reg8.H, reg8.E),
  opcodes.LD_X_Y.bind(undefined, reg8.H, reg8.D),
  opcodes.LD_X_Y.bind(undefined, reg8.H, reg8.H),
  opcodes.LD_X_Y.bind(undefined, reg8.H, reg8.L),
  opcodes.LD_X_mYZ.bind(undefined, reg8.H, reg8.H, reg8.L),
  opcodes.LD_X_Y.bind(undefined, reg8.L, reg8.B),
  opcodes.LD_X_Y.bind(undefined, reg8.L, reg8.C),
  opcodes.LD_X_Y.bind(undefined, reg8.L, reg8.D),
  opcodes.LD_X_Y.bind(undefined, reg8.L, reg8.E),
  opcodes.LD_X_Y.bind(undefined, reg8.L, reg8.H),
  opcodes.LD_X_Y.bind(undefined, reg8.L, reg8.L),
  opcodes.LD_X_mYZ.bind(undefined, reg8.L, reg8.H, reg8.L),
  opcodes.LD_X_Y.bind(undefined, reg8.L, reg8.A),
  //0x70
  opcodes.LD_mXY_Z.bind(undefined, reg8.H, reg8.L, reg8.B),
  opcodes.LD_mXY_Z.bind(undefined, reg8.H, reg8.L, reg8.C),
  opcodes.LD_mXY_Z.bind(undefined, reg8.H, reg8.L, reg8.D),
  opcodes.LD_mXY_Z.bind(undefined, reg8.H, reg8.L, reg8.E),
  opcodes.LD_mXY_Z.bind(undefined, reg8.H, reg8.L, reg8.H),
  opcodes.LD_mXY_Z.bind(undefined, reg8.H, reg8.L, reg8.L),
  opcodes.HALT,
  opcodes.LD_mXY_Z.bind(undefined, reg8.H, reg8.L, reg8.A),
  opcodes.LD_mXY_Z.bind(undefined, reg8.H, reg8.L, reg8.C),
  opcodes.LD_X_Y.bind(undefined, reg8.A, reg8.B),
  opcodes.LD_X_Y.bind(undefined, reg8.A, reg8.C),
  opcodes.LD_X_Y.bind(undefined, reg8.A, reg8.D),
  opcodes.LD_X_Y.bind(undefined, reg8.A, reg8.E),
  opcodes.LD_X_Y.bind(undefined, reg8.A, reg8.H),
  opcodes.LD_X_Y.bind(undefined, reg8.A, reg8.L),
  opcodes.LD_X_mYZ.bind(undefined, reg8.A, reg8.H, reg8.L),
  opcodes.LD_X_Y.bind(undefined, reg8.A, reg8.A),
  //0x80
  opcodes.ADD_X_Y.bind(undefined, reg8.A, reg8.B),
  opcodes.ADD_X_Y.bind(undefined, reg8.A, reg8.C),
  opcodes.ADD_X_Y.bind(undefined, reg8.A, reg8.D),
  opcodes.ADD_X_Y.bind(undefined, reg8.A, reg8.E),
  opcodes.ADD_X_Y.bind(undefined, reg8.A, reg8.H),
  opcodes.ADD_X_Y.bind(undefined, reg8.A, reg8.L),
  opcodes.ADD_X_mYZ.bind(undefined, reg8.A, reg8.H, reg8.L)



]